# Version
V1.0.0:
  - '(\[V1.0.0\]|バージョン(: |：)1.0.0)'

V1.0.1:
  - '(\[V1.0.1\]|バージョン(: |：)1.0.1)'

バージョン未定:
  - 'バージョン(: |：)未定'

# Issue Type
バグ :bug:: 
  - 'タイプ(: |：)バグ'

仕様変更 :memo::
  - 'タイプ(: |：)仕様変更'

Todo :page_facing_up::
  - 'タイプ(: |：)[Tt][Oo][Dd][Oo]'

# Rank
Rank A:
  - 'ランク(: |：)A'

Rank B:
  - 'ランク(: |：)B'

Rank C:
  - 'ランク(: |：)C'

Rank D:
  - 'ランク(: |：)D'

# Assignee
担当未定:
  - '担当(: |：)未定'