# Version
V5.1.3:
  - '\[V5.1.3\]'

V5.1.2:
  - '\[V5.1.2\]'

# Issue Type
バグ :bug:: 
  - 'タイプ(: |：)バグ'

仕様変更 :memo::
  - 'タイプ(: |：)仕様変更'

Todo :page_facing_up::
  - 'タイプ(: |：)[Tt][Oo][Dd][Oo]'

# Rank
Rank A:
  - 'ランク(: |：)A'

Rank B:
  - 'ランク(: |：)B'

Rank C:
  - 'ランク(: |：)C'

Rank D:
  - 'ランク(: |：)D'

