# https://github.com/github/issue-labeler

name: "Issue Labeler"

on:
  issues:
    types: [opened, edited]

permissions:
  issues: write
  contents: read

jobs:
  triage:
    runs-on: ubuntu-latest
    steps:
    - uses: github/issue-labeler@v3.2
      with:
        configuration-path: .github/labeler.yml
        not-before: 2023-10-20T00:00:00Z
        include-title: 1
        include-body: 1
        sync-labels: 1 # By default, labels that no longer match are not removed from the issue. To enable this functionality, explicity set sync-labels to 1.
        enable-versioned-regex: 1
        versioned-regex: 'issue_labeler_regex_version=(\d+)'
        # body-missing-regex-label: 'broken-template'
        repo-token: ${{ github.token }}